### PR TITLE
adding download module

### PR DESCRIPTION
**Pull request by choldgraf**
This adds some functionality to download specific weeks of data. See a demo for how it could be used here:

https://github.com/choldgraf/earth-analytics-python/blob/add_downloads/notebooks/utils/demos/download_data.ipynb

### CODE REVIEW

**Comment by lwasser** [comment]
hey @choldgraf -- is the earthlab 'et' import what's in another repo? can you send me a link to that repo? I'd like this repo to be self sufficient - ie no external dependencies. i'm just wondering what that script does. in R i think you can just download.file and then unzip in a few lines of code! i know python is different :)

**Comment by choldgraf** [comment]
`earthlab` is a little module that I wrote for the class, here's the `.io` section of it:

https://github.com/choldgraf/earth-analytics-python/blob/0f4e1f58a78786c95371c21aefac0ba894c1600e/earthlab/io.py

That relies on a module called `connectortools` which you can install online. I can make it available with `pip` at some point as well so you can just do `pip install connectortools` or whatever it's called.

**Comment by lwasser** [comment]
Cool thanks. So if we actually have this as a command line function eventually it could fit into a make workflow!

**Comment by choldgraf** [comment]
yeah for sure - it could make things more scriptable in general

**Comment by choldgraf** [comment]
(btw feel free to merge if you want to, otherwise I'll merge in a little bit, just wanna make sure that you see the code as it's coming in)

**Comment by lwasser** [comment]
Great! Thanks a lot. I think this will be good.

**Comment by lwasser** [comment]
Thank you for this. Yes the PR's are nice to be able to see! you should have super powers for this repo now too however. let me know if you dont

**Comment by choldgraf** [comment]
sounds good - I'll push directly to master for smaller things then, and can do PRs for larger things we should discuss

**Comment by lwasser** [comment]
Great!! Yes however you’d like to work. It works great for me that whatever you’d like feedback on – you submit a PR will be good.

**Pull request merged**
