### PR TITLE
week 2 draft

### PR DESCRIPTION
**Pull request by choldgraf**
This should be all course materials from week 2, though note that for the lecture stuff I'm using the non-updated material. We should make sure there's not too much of a difference between them.

### CODE REVIEW

**Comment by lwasser** [comment]
awesome @choldgraf !! i have a meeting at noon but i'll have a look at this - this afternoon. I"m more than happy to ensure the content part is current. 

Is the last part of week 5 still left? no rush i'm just asking. 
Thank you!

**Comment by choldgraf** [comment]
sounds good - are we still planning to skype this afternoon?

And re: week 5, I still need to finish that one. Just had a bit of time so wanted to knock out most of week 2 to try and get us back to schedule more/less.

**Comment by lwasser** [comment]
Yes!! 2pm you time 3pm my time Skype?

Leah

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser

________________________________

**Comment by choldgraf** [comment]
yep

**Comment by lwasser** [comment]
hey @choldgraf  - are you ok with us moving to a new directory structure as follows:
https://github.com/earthlab/earth-analytics-python/tree/week-05-edits/notebooks
 	final-notebooks 	 
	template-notebooks 	 
	templates

Notice that my week 5 edits use this structure. i haven't merged to master yet but once we're in agreement i will!

**Pull request merged**
