### PR TITLE
adding notebook to md conversion

### PR DESCRIPTION
**Pull request by choldgraf**
This adds a prototype notebook that converts our "finalized" notebooks to markdown in the appropriate folder. It should also dump images into the appropriate folder as well. We can clean it up quite a bit and I still need to add the "diff" ing so that it only builds notebooks that have changed, but it's a good start.

### CODE REVIEW

**Comment by choldgraf** [comment]
Oh - this also adds in two other notebooks that somehow got delete in the great mergeathon of a few days back.

**Comment by lwasser** [comment]
awesome @choldgraf So if i run the  template notebook it will batch process rmd to notebook and if i run the other it will batch convert notebooks to md files? I'll give this a go today! 

General question. Is there a reason to do the utility work in notebooks vs just using .py scripts? I'm just thinking about a future make workflow. I'm fine with either and know it's easy to convert i'm  just wondering . i suppose this allows us to really document well.

**Comment by lwasser** [comment]
ok @choldgraf there are .md files now in the template dir. we need to remove those as they will get built byjekyll! i'm going to do that now and push it back up. then i'll look at the script more closely and give it a run .

**Comment by lwasser** [comment]
also there are processing scripts in the templates folder and utils. can we keep all scripts in utils?

**Comment by lwasser** [comment]
ERROR - @choldgraf i believe the error is because it's trying to write the files to a temporary dir that doesn't exist on my computer. can we please add some code that creates this dir for the build and then deletes it at the end? 

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-ee22b699535b> in <module>()
     38     # Write the file
     39     path_save_tmp_file = os.path.join('./tmp', path_tmp_file)
---> 40     nf.write(ntbk, path_save_tmp_file)
     41 
     42     # Call nbconvert

/Users/lewa8222/anaconda/lib/python3.6/site-packages/nbformat/__init__.py in write(nb, fp, version, **kwargs)
    161     """
    162     if isinstance(fp, (py3compat.unicode_type, bytes)):
--> 163         with io.open(fp, 'w', encoding='utf-8') as f:
    164             return write(nb, f, version=version, **kwargs)
    165 

FileNotFoundError: [Errno 2] No such file or directory: './tmp/2016-12-06-erosion-02-precip-discharge-r-example.ipynb'
```

**Comment by choldgraf** [comment]
Huh - there shouldn't be any processing scripts outside of utils, so sure we can remove those. Also eventually we wanna turn the `ipynb` into a `.py` script but I'm just using a notebook to prototype it. This isn't a final version.

re: the error, I can add in that bit of code in the next PR.

**Comment by lwasser** [comment]
great!! thanks. there are what look like processing files here

https://github.com/earthlab/earth-analytics-python/tree/master/notebooks/template-notebooks

* https://github.com/earthlab/earth-analytics-python/blob/master/notebooks/template-notebooks/markdown_to_ntbk.ipynb
* https://github.com/earthlab/earth-analytics-python/blob/master/notebooks/template-notebooks/ntbk_to_jekyllmarkdown.ipynb

etc... some have code and some dont ! maybe just leftovers? thanks so much!

**Comment by choldgraf** [comment]
huh, that is weird...looks like they're duplicates of what is in `utils`. They must have been moved somehow ??

**Comment by lwasser** [comment]
maybe? 
Also - how would you like to work - there are a few other tweaks like 
`_posts/course-materials/earth-analytics/` needs to be 
`_posts/course-materials/earth-analytics-python/` 

Super minor but will be important to not overwrite my other course :) 
Do you want me to comment on the next PR line by line? again trying to avoid merge conflicts! :)

**Comment by choldgraf** [comment]
I don't think merge conflicts will pop up so long as we remember to always branch off of the latest master, and don't edit the same files. I'm happy to make small changes etc if you wanna just list them in the PR!

**Comment by lwasser** [comment]
ok! i don't want to be too nit picky and make you make too many tiny changes. i'm excited to see this coming together! The build is working well locally short of the missing images and such which we will slowly work through! :) thanks so much @choldgraf

**Pull request merged**
